// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gczkuolrxmwfwhcgllva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdjemt1b2xyeG13ZndoY2dsbHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTU4MTEsImV4cCI6MjA2MTc5MTgxMX0.KJBVi5imwFz9SmaXxDmNZ-nrhmk9F22dNtKGZEU-LEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);